server:
  port: 8082

spring:
  application:
    name: comment-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/comment_db
      
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/blog-microservices
          jwk-set-uri: http://localhost:8080/realms/blog-microservices/protocol/openid-connect/certs


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost

resilience4j:
  circuitbreaker:
    instances:
      postService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
management:
  logging:
    export:
      enabled: true
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1
