server:
  port: 8081

spring:
  application:
    name: post-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/blog_db


  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          default:
            connectTimeout: 2000
            readTimeout: 2000
            loggerLevel: basic

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost


resilience4j:
  circuitbreaker:
    instances:
      commentService:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        registerHealthIndicator: true
        # Record specific exceptions to trigger circuit breaker
        recordExceptions:
          - feign.FeignException$ServiceUnavailable
          - java.util.concurrent.TimeoutException
          - java.net.ConnectException

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers
  endpoint:
    health:
      show-details: always
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
      export:
        enabled: true
